import type { Metadata } from "next";
import { Provider } from "@repo/ui/provider";
import { TRPCProvider } from "./_trpc/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TRPCProvider>
          <Provider>{children}</Provider>
        </TRPCProvider>
      </body>
    </html>
  );
}
